### ISSUE TITLE
docs.fluxcd.io is broken

### ISSUE THREAD

**Issue by CameronNemo** [fluxcd/fluxcd.io#12]

**Comment by stefanprodan** [comment]
We have transferred the fluxcd.io domain to Linux Foundation, please bear with us while they solve the DNS issues. We have no control over it anymore but we've notified LF about the missing records.

**Comment by caniszczyk** [comment]
Flux maintainers should have Netlify DNS access to control DNS settings so this should be fixable by the Flux maintainers.

**Comment by stefanprodan** [comment]
@caniszczyk  I've logged it with my GitHub account in Netlify and it's nothing there

**Comment by stefanprodan** [comment]
@caniszczyk I got your invite but I can't manage sub domains from there, I'm referring to the  `charts.fluxcd.io` and `docs.fluxcd.io` CNAMEs

**Comment by lucperkins** [comment]
@stefanprodan https://app.netlify.com/teams/flux-nzla5m8/dns/fluxcd.io

**Comment by stefanprodan** [comment]
@lucperkins thanks! I've been looking at https://app.netlify.com/sites/fluxcd/settings/domain 🤦‍♂ 

Sorry for all the noise!

**Comment by lucperkins** [comment]
@stefanprodan No worries! I occasionally forget that that’s at the account level and not the site level 😂
